# Modular-monolith FastAPI template — task runner.
# Requires: Python 3.14+, uv, just, docker (for Postgres).
set dotenv-load := true
set shell := ["bash", "-cu"]

[private]
default:
    @just --list

# ── development ──
[doc('Start the API locally with hot-reload on port 8000 (Swagger at /api/v1/docs).')]
dev-api:
    uv run uvicorn --app-dir src --reload --reload-dir src --host 0.0.0.0 --port 8000 --factory api.entrypoints.main:create_app

# ── docker / database ──
[doc('Start PostgreSQL 17 in Docker.')]
db:
    docker compose up postgres -d

[doc('Stop services (data volumes preserved).')]
db-down:
    docker compose down

[doc('Stop services AND delete the data volume (wipes local Postgres).')]
db-clean:
    docker compose down -v

# ── migrations (Alembic) ──
[doc('Create a new autogenerated migration: just create-migration "message".')]
create-migration message:
    uv run alembic revision --autogenerate -m "{{message}}"

[doc('Apply pending migrations.')]
apply-migration:
    uv run alembic upgrade head

[doc('Roll back the last migration.')]
rollback-migration:
    uv run alembic downgrade -1

# ── quality gates ──
[doc('Run the full test suite.')]
test *args:
    uv run pytest {{args}}

[doc('Run only the architecture tests.')]
arch-test:
    uv run pytest tests/architecture -v

[doc('Run tests with a coverage report.')]
coverage:
    uv run pytest --cov=src/api --cov-report=term-missing

[doc('Run the ruff linter + format check.')]
lint:
    uv run ruff check src/ tests/
    uv run ruff format --check src/ tests/

[doc('Auto-format and auto-fix.')]
format:
    uv run ruff format src/ tests/
    uv run ruff check --fix src/ tests/

[doc('Run the import-linter architecture contracts.')]
lint-imports:
    PYTHONPATH=src uv run lint-imports
